### ISSUE TITLE
Boss timer outdated

### ISSUE THREAD

**Issue by twintower74** [Simego/bdohelper#1]
Your boss spawn times are outdated

**Comment by Simego** [comment]
Are you from NA/EU? i'm going to update them soon (probably today), if you're from SEA, can you send me the boss schedule and server time zone? thanks!

**Comment by Simego** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update NA and EU boss schedule](https://trello.com/c/RH5Qe6Fj/31-update-na-and-eu-boss-schedule)

**Comment by Simego** [comment]
Updated NA,EU and SEA boss schedule, added KR and MENA.
